"""SillyTavern Character Card V2 导出。

SillyTavern 是最流行的开源 AI 聊天 UI（10K+ GitHub stars），
使用 Character Card Specification V2 作为角色卡标准。
格式：JSON（可嵌入 PNG 的 tEXt chunk）。
"""
import json
from pathlib import Path

from ..core.safe import safe_filename


class SillyTavernExporter:
    """导出为 SillyTavern Character Card V2 格式（.json）。"""
    name = "sillytavern"
    extension = ".json"
    label = "SillyTavern (character_card_v2)"

    def export(self, doc, out_dir: str, **kwargs) -> str:
        # 从 system_prompt 提取核心内容
        system_prompt = doc.system_prompt or ""

        # 构建 Character Card V2
        card = {
            "spec": "chara_card_v2",
            "spec_version": "2.0",
            "data": {
                "name": doc.display_name or doc.name,
                "description": _build_description(doc),
                "personality": _build_personality(doc),
                "scenario": doc.relationship or "",
                "first_mes": _build_first_mes(doc),
                "mes_example": _build_mes_example(doc),
                "creator_notes": f"Generated by Alchemy Hive. System prompt included in character_book.",
                "system_prompt": system_prompt,
                "post_history_instructions": "",
                "alternate_greetings": [],
                "character_book": _build_character_book(doc),
                "tags": _extract_tags(doc),
                "creator": "Alchemy Hive",
                "character_version": "1.0",
                "extensions": {},
            },
        }

        safe = safe_filename(doc.name)
        p = Path(out_dir) / f"{safe}.sillytavern.json"
        p.write_text(json.dumps(card, ensure_ascii=False, indent=2), encoding="utf-8")
        return str(p)


def _build_description(doc) -> str:
    """从 PersonaDoc 构建角色描述。"""
    parts = []
    if doc.relationship:
        parts.append(f"关系：{doc.relationship}")
    if doc.relationship_context:
        parts.append(doc.relationship_context)
    if doc.expression_rules:
        parts.append("表达规则：" + "；".join(doc.expression_rules[:5]))
    if doc.signature_phrases:
        parts.append("口头禅：" + "、".join(doc.signature_phrases[:5]))
    return "\n".join(parts) or f"{doc.display_name or doc.name} 的角色描述。"


def _build_personality(doc) -> str:
    """从 PersonaDoc 构建性格描述。"""
    parts = []
    if doc.profile:
        tags = doc.profile.get("tags", [])
        if tags:
            parts.append("性格关键词：" + "、".join(tags[:8]))
    if doc.rhythm:
        parts.append("说话节奏：" + doc.rhythm)
    return "；".join(parts) or "自然、真实。"


def _build_first_mes(doc) -> str:
    """构建第一条消息（开场白）。"""
    if doc.example_replies:
        # 取第一个场景的第一条例句
        for scene, replies in doc.example_replies.items():
            if isinstance(replies, list) and replies:
                return replies[0]
    return f"嗨，我是{doc.display_name or doc.name}。"


def _build_mes_example(doc) -> str:
    """构建示例对话。"""
    examples = []
    if doc.example_replies:
        for scene, replies in list(doc.example_replies.items())[:5]:
            if isinstance(replies, list):
                for reply in replies[:2]:
                    examples.append(f"<START>\n{{{doc.display_name or doc.name}}}: {reply}")
    return "\n\n".join(examples) or f"<START>\n{{{doc.display_name or doc.name}}}: 你好。"


def _build_character_book(doc) -> dict:
    """构建 lorebook（记忆条目）。"""
    entries = []
    for m in doc.memory:
        if isinstance(m, dict):
            entries.append({
                "keys": [m.get("trigger", "")],
                "content": m.get("body", ""),
                "extensions": {},
                "enabled": True,
                "insertion_order": 0,
                "case_sensitive": False,
                "name": m.get("slug", ""),
                "priority": 0,
                "id": len(entries),
                "comment": m.get("significance", ""),
                "selective": False,
                "secondary_keys": [],
                "constant": False,
                "position": "before_char",
            })
    return {
        "name": f"{doc.display_name or doc.name} Lorebook",
        "description": "Auto-generated memory entries from chat distillation.",
        "scan_depth": 50,
        "token_budget": 500,
        "recursive_scanning": False,
        "extensions": {},
        "entries": entries,
    }


def _extract_tags(doc) -> list[str]:
    """从 profile.tags 提取标签。"""
    if doc.profile and isinstance(doc.profile, dict):
        return doc.profile.get("tags", [])[:10]
    return []
